const appData = [
  {
    id: 1,
    image: "https://via.placeholder.com/300x200?text=Hero+Chat",
    title: "Hero Chat",
    companyName: "Hero Inc.",
    description:
      "Hero Chat is a modern communication platform built for fast, secure, and intuitive messaging. It allows individuals and teams to collaborate seamlessly with group chats, file sharing, and AI-powered message summaries. Whether for business or personal use, Hero Chat makes staying connected effortless and fun.",
    size: 45,
    reviews: 2200,
    ratingAvg: 4.6,
    downloads: 1200000,
    ratings: [
      { name: "1 star", count: 50 },
      { name: "2 star", count: 100 },
      { name: "3 star", count: 300 },
      { name: "4 star", count: 700 },
      { name: "5 star", count: 1050 },
    ],
  },
  {
    id: 2,
    image: "https://via.placeholder.com/300x200?text=TaskFlow",
    title: "TaskFlow",
    companyName: "FlowTech",
    description:
      "TaskFlow is a productivity app that helps you organize daily tasks, set priorities, and collaborate with your team in real time. With smart reminders, analytics, and customizable boards, it’s the perfect tool for managing projects of any size. Stay ahead with TaskFlow’s smooth and minimal UI.",
    size: 52,
    reviews: 1800,
    ratingAvg: 4.8,
    downloads: 800000,
    ratings: [
      { name: '1 star', count: 60 },
      { name: '2 star', count: 120 },
      { name: '3 star', count: 250 },
      { name: '4 star', count: 650 },
      { name: '5 star', count: 720 },
    ],
  },
  {
    id: 3,
    image: "https://via.placeholder.com/300x200?text=FitTrack",
    title: "FitTrack",
    companyName: "Wellness Labs",
    description:
      "FitTrack is a comprehensive fitness tracker that logs your workouts, diet, and sleep patterns. It uses machine learning to provide daily health insights and personalized recommendations to help you meet your fitness goals faster. Whether you’re a beginner or athlete, FitTrack keeps you motivated.",
    size: 65,
    reviews: 3400,
    ratingAvg: 4.5,
    downloads: 950000,
    ratings: [
      { name: '1 star', count: 150 },
      { name: '2 star', count: 200 },
      { name: '3 star', count: 500 },
      { name: '4 star', count: 900 },
      { name: '5 star', count: 1650 },
    ],
  },
  {
    id: 4,
    image: "https://via.placeholder.com/300x200?text=PhotoSnap",
    title: "PhotoSnap",
    companyName: "PixelSoft",
    description:
      "PhotoSnap is a simple yet powerful photo editing and sharing app. It features a suite of professional-grade editing tools, filters, and effects, all accessible through an easy-to-use interface. Instantly enhance your photos, share them on social media, and explore trending visuals from around the world.",
    size: 78,
    reviews: 5100,
    ratingAvg: 4.3,
    downloads: 1500000,
    ratings: [
      { name: '1 star', count: 400 },
      { name: '2 star', count: 500 },
      { name: '3 star', count: 900 },
      { name: '4 star', count: 1300 },
      { name: '5 star', count: 2000 },
    ],
  },
  {
    id: 5,
    image: "https://via.placeholder.com/300x200?text=NoteIt",
    title: "NoteIt",
    companyName: "CloudSync",
    description:
      "NoteIt is your digital notebook designed for speed and simplicity. It lets you jot down quick notes, organize to-do lists, and sync them across all devices instantly. With cloud backup and advanced search, NoteIt ensures your ideas are never lost again.",
    size: 34,
    reviews: 900,
    ratingAvg: 4.7,
    downloads: 600000,
    ratings: [
      { name: '1 star', count: 30 },
      { name: '2 star', count: 80 },
      { name: '3 star', count: 120 },
      { name: '4 star', count: 300 },
      { name: '5 star', count: 370 },
    ],
  },
  {
    id: 6,
    image: "https://via.placeholder.com/300x200?text=CookEase",
    title: "CookEase",
    companyName: "Chefify Co.",
    description:
      "CookEase helps you discover delicious recipes tailored to your taste and dietary needs. From healthy breakfasts to gourmet dinners, it offers step-by-step guidance, ingredient lists, and cooking timers. Learn, cook, and share your creations with the vibrant CookEase community.",
    size: 80,
    reviews: 1500,
    ratingAvg: 4.9,
    downloads: 2000000,
    ratings: [
      { name: '1 star', count: 40 },
      { name: '2 star', count: 70 },
      { name: '3 star', count: 200 },
      { name: '4 star', count: 400 },
      { name: '5 star', count: 790 },
    ],
  },
  {
    id: 7,
    image: "https://via.placeholder.com/300x200?text=TravelGo",
    title: "TravelGo",
    companyName: "Skyline Apps",
    description:
      "TravelGo is your personal travel companion, offering flight tracking, hotel booking, and real-time weather updates. Discover hidden gems, save itineraries, and explore destinations effortlessly. With AI-based recommendations, your next adventure is always just a tap away.",
    size: 95,
    reviews: 2400,
    ratingAvg: 4.4,
    downloads: 1700000,
    ratings: [
      { name: '1 star', count: 90 },
      { name: '2 star', count: 150 },
      { name: '3 star', count: 400 },
      { name: '4 star', count: 850 },
      { name: '5 star', count: 910 },
    ],
  },
  {
    id: 8,
    image: "https://via.placeholder.com/300x200?text=BudgetBuddy",
    title: "BudgetBuddy",
    companyName: "FinancePro",
    description:
      "BudgetBuddy is a smart expense tracker that simplifies managing your finances. It automatically categorizes spending, tracks savings goals, and provides insights through interactive charts. Stay financially fit with BudgetBuddy’s clean dashboard and intelligent alerts.",
    size: 58,
    reviews: 1100,
    ratingAvg: 4.8,
    downloads: 1250000,
    ratings: [
      { name: '1 star', count: 20 },
      { name: '2 star', count: 70 },
      { name: '3 star', count: 150 },
      { name: '4 star', count: 400 },
      { name: '5 star', count: 460 },
    ],
  },
  {
    id: 9,
    image: "https://via.placeholder.com/300x200?text=Readly",
    title: "Readly",
    companyName: "BookSpace",
    description:
      "Readly lets you access thousands of eBooks, audiobooks, and magazines anytime, anywhere. With adjustable fonts, offline access, and smart recommendations, it transforms how you read. Track your reading progress and connect with other readers across genres.",
    size: 42,
    reviews: 1900,
    ratingAvg: 4.9,
    downloads: 900000,
    ratings: [
      { name: '1 star', count: 40 },
      { name: '2 star', count: 100 },
      { name: '3 star', count: 200 },
      { name: '4 star', count: 700 },
      { name: '5 star', count: 860 },
    ],
  },
  {
    id: 10,
    image: "https://via.placeholder.com/300x200?text=GameHub",
    title: "GameHub",
    companyName: "Arcadia Studios",
    description:
      "GameHub is the ultimate gaming companion, bringing you news, reviews, and live event updates. Follow your favorite streamers, compete in leaderboards, and get early access to new releases. GameHub keeps every gamer in the loop.",
    size: 120,
    reviews: 3200,
    ratingAvg: 4.2,
    downloads: 2200000,
    ratings: [
      { name: '1 star', count: 300 },
      { name: '2 star', count: 400 },
      { name: '3 star', count: 700 },
      { name: '4 star', count: 900 },
      { name: '5 star', count: 900 },
    ],
  },
  {
    id: 11,
    image: "https://via.placeholder.com/300x200?text=CalmMind",
    title: "CalmMind",
    companyName: "Mindful Tech",
    description:
      "CalmMind is a meditation and relaxation app that helps you reduce stress and improve sleep through guided sessions. With soothing music and daily mindfulness reminders, CalmMind helps you focus and recharge your mind every day.",
    size: 60,
    reviews: 2700,
    ratingAvg: 4.8,
    downloads: 1400000,
    ratings: [
      { name: '1 star', count: 40 },
      { name: '2 star', count: 90 },
      { name: '3 star', count: 200 },
      { name: '4 star', count: 600 },
      { name: '5 star', count: 1770 },
    ],
  },
  {
    id: 12,
    image: "https://via.placeholder.com/300x200?text=Weatherly",
    title: "Weatherly",
    companyName: "SkyTech",
    description:
      "Weatherly gives you hyper-accurate weather forecasts with real-time radar maps and alerts. Plan your week or trip ahead with 7-day insights and customizable themes. Simple, elegant, and reliable — Weatherly makes checking weather a breeze.",
    size: 50,
    reviews: 1900,
    ratingAvg: 4.7,
    downloads: 1800000,
    ratings: [
      { name: '1 star', count: 80 },
      { name: '2 star', count: 100 },
      { name: '3 star', count: 250 },
      { name: '4 star', count: 600 },
      { name: '5 star', count: 870 },
    ],
  },
  {
    id: 13,
    image: "https://via.placeholder.com/300x200?text=EduPro",
    title: "EduPro",
    companyName: "LearnLabs",
    description:
      "EduPro is a learning management platform offering interactive courses, quizzes, and skill-based certifications. It adapts to your pace and provides AI-driven learning paths to help you master any subject efficiently.",
    size: 90,
    reviews: 2500,
    ratingAvg: 4.9,
    downloads: 2000000,
    ratings: [
      { name: '1 star', count: 50 },
      { name: '2 star', count: 100 },
      { name: '3 star', count: 150 },
      { name: '4 star', count: 700 },
      { name: '5 star', count: 1500 },
    ],
  },
  {
    id: 14,
    image: "https://via.placeholder.com/300x200?text=ShopSmart",
    title: "ShopSmart",
    companyName: "RetailSync",
    description:
      "ShopSmart makes shopping smarter by comparing prices across online stores, tracking deals, and suggesting coupons in real time. Save money effortlessly while enjoying personalized product recommendations.",
    size: 85,
    reviews: 3100,
    ratingAvg: 4.4,
    downloads: 2100000,
    ratings: [
      { name: '1 star', count: 200 },
      { name: '2 star', count: 300 },
      { name: '3 star', count: 500 },
      { name: '4 star', count: 800 },
      { name: '5 star', count: 1300 },
    ],
  },
  {
    id: 15,
    image: "https://via.placeholder.com/300x200?text=Streamify",
    title: "Streamify",
    companyName: "NextWave Media",
    description:
      "Streamify brings your favorite movies, shows, and live TV channels into one seamless app. With adaptive streaming, offline downloads, and curated playlists, it’s your all-in-one entertainment hub.",
    size: 150,
    reviews: 6000,
    ratingAvg: 4.5,
    downloads: 5000000,
    ratings: [
      { name: '1 star', count: 500 },
      { name: '2 star', count: 800 },
      { name: '3 star', count: 1200 },
      { name: '4 star', count: 1600 },
      { name: '5 star', count: 1900 },
    ],
  },
  {
    id: 16,
    image: "https://via.placeholder.com/300x200?text=Musicly",
    title: "Musicly",
    companyName: "SoundSphere",
    description:
      "Musicly is a streaming app designed for music lovers. Create playlists, explore new artists, and experience high-quality audio streaming. With AI-driven recommendations, Musicly curates tracks that suit your mood perfectly.",
    size: 98,
    reviews: 3700,
    ratingAvg: 4.8,
    downloads: 3500000,
    ratings: [
      { name: '1 star', count: 120 },
      { name: '2 star', count: 180 },
      { name: '3 star', count: 400 },
      { name: '4 star', count: 800 },
      { name: '5 star', count: 2200 },
    ],
  },
  {
    id: 17,
    image: "https://via.placeholder.com/300x200?text=DocuSafe",
    title: "DocuSafe",
    companyName: "SecureCloud",
    description:
      "DocuSafe provides secure, encrypted document storage in the cloud. Easily upload, share, and manage your files across devices with full privacy protection and two-factor authentication.",
    size: 76,
    reviews: 1900,
    ratingAvg: 4.6,
    downloads: 900000,
    ratings: [
      { name: '1 star', count: 70 },
      { name: '2 star', count: 120 },
      { name: '3 star', count: 300 },
      { name: '4 star', count: 700 },
      { name: '5 star', count: 710 },
    ],
  },
  {
    id: 18,
    image: "https://via.placeholder.com/300x200?text=NewsWave",
    title: "NewsWave",
    companyName: "MediaCore",
    description:
      "NewsWave aggregates breaking news from top global sources and presents it in an easy-to-read, distraction-free interface. Stay informed with real-time updates, personalized feeds, and dark mode support.",
    size: 60,
    reviews: 1300,
    ratingAvg: 4.5,
    downloads: 1100000,
    ratings: [
      { name: '1 star', count: 100 },
      { name: '2 star', count: 150 },
      { name: '3 star', count: 300 },
      { name: '4 star', count: 500 },
      { name: '5 star', count: 250 },
    ],
  },
  {
    id: 19,
    image: "https://via.placeholder.com/300x200?text=Langify",
    title: "Langify",
    companyName: "LingoWorks",
    description:
      "Langify helps you learn new languages through short interactive lessons and daily challenges. It uses gamification and real-life examples to keep you engaged while mastering pronunciation and vocabulary.",
    size: 70,
    reviews: 2800,
    ratingAvg: 4.9,
    downloads: 2700000,
    ratings: [
      { name: '1 star', count: 50 },
      { name: '2 star', count: 90 },
      { name: '3 star', count: 200 },
      { name: '4 star', count: 800 },
      { name: '5 star', count: 1660 },
    ],
  },
  {
    id: 20,
    image: "https://via.placeholder.com/300x200?text=HealthSync",
    title: "HealthSync",
    companyName: "MediCore Labs",
    description:
      "HealthSync connects with your smart devices to track vital stats like heart rate, steps, and hydration levels. It provides weekly health reports and lifestyle tips to help you stay in shape and maintain balance.",
    size: 85,
    reviews: 2600,
    ratingAvg: 4.7,
    downloads: 1500000,
    ratings: [
      { name: '1 star', count: 80 },
      { name: '2 star', count: 120 },
      { name: '3 star', count: 300 },
      { name: '4 star', count: 700 },
      { name: '5 star', count: 1400 },
    ],
  },
];

export default appData;
